# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: post_text_request.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'post_text_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import protos.type_pb2 as type_pb2
import protos.prompt_pb2 as prompt_pb2
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17post_text_request.proto\x12\x03llm\x1a\ntype.proto\x1a\x0cprompt.proto\"L\n\x0fGenerateRequest\x12\x1c\n\x04type\x18\x01 \x01(\x0e\x32\x0e.llm.ProtoType\x12\x1b\n\x06prompt\x18\x02 \x01(\x0b\x32\x0b.llm.Promptb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'post_text_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEREQUEST']._serialized_start=58
  _globals['_GENERATEREQUEST']._serialized_end=134
# @@protoc_insertion_point(module_scope)
