// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "llm_service.proto" (package "llm", syntax proto3)
// tslint:disable
import { GenerateResponse } from "./post_text_response";
import { GenerateRequest } from "./post_text_request";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service llm.LLM
 */
export const LLM = new ServiceType("llm.LLM", [
    { name: "GenerateText", options: {}, I: GenerateRequest, O: GenerateResponse }
]);
