// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "post_text_response.proto" (package "llm", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Prompt } from "./prompt";
/**
 * @generated from protobuf message llm.GenerateResponse
 */
export interface GenerateResponse {
    /**
     * @generated from protobuf field: llm.Prompt prompt = 1
     */
    prompt?: Prompt;
}
// @generated message type with reflection information, may provide speed optimized methods
class GenerateResponse$Type extends MessageType<GenerateResponse> {
    constructor() {
        super("llm.GenerateResponse", [
            { no: 1, name: "prompt", kind: "message", T: () => Prompt }
        ]);
    }
    create(value?: PartialMessage<GenerateResponse>): GenerateResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GenerateResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GenerateResponse): GenerateResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* llm.Prompt prompt */ 1:
                    message.prompt = Prompt.internalBinaryRead(reader, reader.uint32(), options, message.prompt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GenerateResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* llm.Prompt prompt = 1; */
        if (message.prompt)
            Prompt.internalBinaryWrite(message.prompt, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message llm.GenerateResponse
 */
export const GenerateResponse = new GenerateResponse$Type();
