// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "role.proto" (package "llm", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum llm.Role
 */
export enum Role {
    /**
     * @generated from protobuf enum value: ROLE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: ROLE_ASSISTANT = 1;
     */
    ASSISTANT = 1,
    /**
     * @generated from protobuf enum value: ROLE_USER = 2;
     */
    USER = 2,
    /**
     * @generated from protobuf enum value: ROLE_SYSTEM = 3;
     */
    SYSTEM = 3
}
