// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "type.proto" (package "llm", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum llm.ProtoType
 */
export enum ProtoType {
    /**
     * @generated from protobuf enum value: TYPE_UNSPECIFIED = 0;
     */
    TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: TYPE_MESSAGE = 1;
     */
    TYPE_MESSAGE = 1,
    /**
     * @generated from protobuf enum value: TYPE_SEARCH = 2;
     */
    TYPE_SEARCH = 2,
    /**
     * @generated from protobuf enum value: TYPE_THINK = 3;
     */
    TYPE_THINK = 3
}
