// source: get_content_response.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var scrape_pb = require('./scrape_pb.js');
goog.object.extend(proto, scrape_pb);
goog.exportSymbol('proto.scrape.GetScrapedResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.scrape.GetScrapedResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.scrape.GetScrapedResponse.repeatedFields_, null);
};
goog.inherits(proto.scrape.GetScrapedResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.scrape.GetScrapedResponse.displayName = 'proto.scrape.GetScrapedResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.scrape.GetScrapedResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.scrape.GetScrapedResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.scrape.GetScrapedResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.scrape.GetScrapedResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scrape.GetScrapedResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    scrapeList: jspb.Message.toObjectList(msg.getScrapeList(),
    scrape_pb.Scrape.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.scrape.GetScrapedResponse}
 */
proto.scrape.GetScrapedResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.scrape.GetScrapedResponse;
  return proto.scrape.GetScrapedResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.scrape.GetScrapedResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.scrape.GetScrapedResponse}
 */
proto.scrape.GetScrapedResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new scrape_pb.Scrape;
      reader.readMessage(value,scrape_pb.Scrape.deserializeBinaryFromReader);
      msg.addScrape(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.scrape.GetScrapedResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.scrape.GetScrapedResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.scrape.GetScrapedResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.scrape.GetScrapedResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScrapeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      scrape_pb.Scrape.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Scrape scrape = 1;
 * @return {!Array<!proto.scrape.Scrape>}
 */
proto.scrape.GetScrapedResponse.prototype.getScrapeList = function() {
  return /** @type{!Array<!proto.scrape.Scrape>} */ (
    jspb.Message.getRepeatedWrapperField(this, scrape_pb.Scrape, 1));
};


/**
 * @param {!Array<!proto.scrape.Scrape>} value
 * @return {!proto.scrape.GetScrapedResponse} returns this
*/
proto.scrape.GetScrapedResponse.prototype.setScrapeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.scrape.Scrape=} opt_value
 * @param {number=} opt_index
 * @return {!proto.scrape.Scrape}
 */
proto.scrape.GetScrapedResponse.prototype.addScrape = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.scrape.Scrape, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.scrape.GetScrapedResponse} returns this
 */
proto.scrape.GetScrapedResponse.prototype.clearScrapeList = function() {
  return this.setScrapeList([]);
};


goog.object.extend(exports, proto.scrape);
