// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "scrape_service.proto" (package "scrape", syntax proto3)
// tslint:disable
import { GetScrapedResponse } from "./get_content_response";
import { GetScrapeRequest } from "./get_content_request";
import { ServiceType } from "@protobuf-ts/runtime-rpc";
/**
 * @generated ServiceType for protobuf service scrape.ScraperService
 */
export const ScraperService = new ServiceType("scrape.ScraperService", [
    { name: "GetScrapedText", options: {}, I: GetScrapeRequest, O: GetScrapedResponse }
]);
